//resolvers += Resolver.sonatypeRepo("releases")
addSbtPlugin("io.get-coursier" % "sbt-coursier"   % "1.0.2")
addSbtPlugin("ch.epfl.scala"   % "sbt-scalafix"   % "0.9.5")
addSbtPlugin("com.geirsson"    % "sbt-ci-release" % "1.2.6")
addSbtPlugin("ch.epfl.scala"   % "sbt-bloop"      % "1.2.5")
addSbtPlugin("org.scalameta"   % "sbt-scalafmt"   % "2.0.0")
